name: Update V2Ray Configs

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write      # اجازه نوشتن فایل

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python update_v2ray_configs.py
